compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"

yarnPath: .yarn/releases/yarn-4.4.1.cjs

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
