local_backend: true
backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "src/lib/config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "baseUrl"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "siteTitle"
            widget: "string"
          - label: "Site description"
            name: "siteDescription"
            widget: "string"
          - label: "Site keywords"
            name: "siteKeywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitterAccount"
            widget: "string"

  - name: testimonials
    label: Testimonials
    folder: src/markdown/testimonials
    extension: mdx
    format: frontmatter
    create: true
    slug: "{{fields.name}}"
    identifier_field: name
    summary: "{{name}}"
    fields:
      - label: Name
        name: name
        widget: string
      - label: Role
        name: role
        widget: string
      - label: Highlight
        name: highlight
        widget: boolean
        default: false
      - label: Headshot
        name: headshot
        widget: image
      - label: Body
        name: body
        widget: markdown
        # Don't allow any custom components within testimonials
        editor_components: []

  - name: papers
    label: Shop Papers
    folder: src/markdown/papers
    extension: mdx
    format: frontmatter
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.slug}}"
    identifier_field: slug
    summary: "{{headline}}"
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Headline
        name: headline
        widget: string
      - label: Published Date
        name: date
        widget: datetime
        date_format: MM/DD/YYYY
        time_format: HH:mm
      - label: Snippet
        name: snippet
        widget: text
      - label: Body
        name: body
        widget: markdown

  - name: pages
    label: Pages
    folder: src/markdown/pages
    extension: mdx
    format: frontmatter
    create: true
    slug: "{{fields.slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: Slug
        name: slug
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Heading
        name: heading
        widget: string
        required: false
      - label: Subheading
        name: subheading
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
