name: deploy

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.json', '**.mdx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Export pages
        run: yarn export

      # Deploy public pages to GCS bucket fronted by Cloud CDN
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: centering-oxide-347014
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          cli: gsutil
          args: -h "Cache-Control:public, max-age=3600" -m cp -z js,css,html,json -r "dist/*" gs://www-nytimesguild-org/

      # Invalidate the CDN cache after updating the files in the bucket, so that
      # clients always get the latest version of the site
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: centering-oxide-347014
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: compute url-maps invalidate-cdn-cache nytimesguild-org-lb --async --path "'/*'"
