name: sync-mirror

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Fetch full repo history; necessory to update mirror!
          fetch-depth: 0

      - name: Create deploy key
        env:
          SYNC_MIRROR_DEPLOY_KEY: ${{ secrets.SYNC_MIRROR_DEPLOY_KEY }}
        run: |
          echo $SYNC_MIRROR_DEPLOY_KEY | base64 -d > ./deploy_key
          chmod 600 ./deploy_key

      - name: Fetch mirror
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ./deploy_key
          git remote add mirror git@github.com:newsguildny/nytimesguild.org.git
          git fetch mirror main

      - name: Push to mirror
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ./deploy_key
          git push mirror main
